# https://docs.github.com/en/packages/managing-github-packages-using-github-actions-workflows/publishing-and-installing-a-package-with-github-actions
name: Build website Docker image
on:
  push:
    branches: ['master']

# Defines two custom environment variables for the workflow. These are used for the Container registry domain, and a name for the Docker image that this workflow builds.
env:
  REGISTRY: ghcr.io
  IMAGE_LABEL: mapwatch.erosson.org

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    # Sets the permissions granted to the `GITHUB_TOKEN` for the actions in this job.
    permissions:
      contents: read
      packages: write
      id-token: write  # https://github.com/marketplace/actions/attest-build-provenance
      attestations: write
      #
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      # Uses the `docker/login-action` action to log in to the Container registry registry using the account and password that will publish the packages. Once published, the packages are scoped to the account defined here.
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      # This step uses [docker/metadata-action](https://github.com/docker/metadata-action#about) to extract tags and labels that will be applied to the specified image. The `id` "meta" allows the output of this step to be referenced in a subsequent step. The `images` value provides the base name for the tags and labels.
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_LABEL }}
      # This step uses the `docker/build-push-action` action to build the image, based on your repository's `Dockerfile`. If the build succeeds, it pushes the image to GitHub Packages.
      # It uses the `context` parameter to define the build's context as the set of files located in the specified path. For more information, see "[Usage](https://github.com/docker/build-push-action#usage)" in the README of the `docker/build-push-action` repository.
      # It uses the `tags` and `labels` parameters to tag and label the image with the output from the "meta" step.
      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      
      # This step generates an artifact attestation for the image, which is an unforgeable statement about where and how it was built. It increases supply chain security for people who consume the image. For more information, see "[AUTOTITLE](/actions/security-guides/using-artifact-attestations-to-establish-provenance-for-builds)." 
      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_LABEL }}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
      
      - name: Trigger combined static-site build and deploy
        # https://docs.github.com/en/rest/repos/repos?apiVersion=2022-11-28#create-a-repository-dispatch-event
        run: |
            curl -L --fail-with-body \
              -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer $GH_TOKEN_INFRA_BUILD_DOCKER_IMAGE" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              https://api.github.com/repos/$TARGET/dispatches \
              -d '{"event_type":"build-docker-image","client_payload":{"source": "$REGISTRY/$IMAGE_NAME", "repo": "$REPOSITORY" }}'
        env: 
          TARGET: erosson/infra
          REGISTRY: ${{ env.REGISTRY }}
          IMAGE_NAME: ${{ github.repository_owner }}/${{ env.IMAGE_LABEL }}
          REPOSITORY: ${{ github.repository }}
          GH_TOKEN_INFRA_BUILD_DOCKER_IMAGE: ${{ secrets.GH_TOKEN_INFRA_BUILD_DOCKER_IMAGE }}

      - name: Delete old Docker images
        uses: snok/container-retention-policy@v2
        with:
          image-names: ${{ env.IMAGE_LABEL }}
          cut-off: 3 days ago UTC
          keep-at-least: 5
          skip-tags: master
          account-type: personal
          token: ${{ secrets.GITHUB_TOKEN }}
          token-type: github-token
