name: pull-request-ci
on: [pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      # https://docs.github.com/en/free-pro-team@latest/actions/guides/building-and-testing-nodejs
      - uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - run: yarn --frozen-lockfile
      - run: yarn test
      - run: yarn build --ignore @mapwatch/electron2
